apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: nodejs-lambda-template
  title: Nodejs Lambda Function
  description: Create a nodejs hello world lambda function
  tags:
    - experimental
    - nodejs
spec:
  owner: Stockholm@team.telstra.com
  templater: cookiecutter
  type: service
  path: "."
  schema:
    required:
      - project_name
      - description
      - lambda.lambda_function_name
      - lambda.runtime
    properties:
      project_name:
        title: Project Directory Name
        type: string
        description: Name of your project directory
        default: nodejs-lambda
      
      description:
        title: Description
        type: string
        description: Description of the component
        default: NodeJS template for lambda deployment

      lambda:
        title: Lambda Function Inputs
        type: object
        properties:
          lambda_function_name:
            title: Function Name
            type: string
            description: Enter a Name for your Lambda Function
            default: lambda1
          runtime:
            title: Runtime
            type: string
            description: Choose runtime for your lambda function 
            enum:
              - nodejs12
              - nodejs10
            default: nodejs12

      bamboo:
        title: Bamboo Specs
        type: object
        properties:
          create_bamboo_specs:
            title: Create Bamboo Specs
            type: boolean
            description: Please select if you want to create bamboo-specs or not?
            enum:
              - True
              - False
            default: True
          team_name:
            title: Team Name
            type: string
            description: Enter Your Team Name
            default: Stockholm
          plan_key:
            title: Bamboo Project Key 
            type: string
            description: Bamboo project key (try use your existing project e.g. STOC)
            default: STOC
          bamboo_plan_key:
            title: Bamboo Build Plan Key
            type: string
            description: Bamboo build plan key (e.g. MYSERVICEV2)
            default: "bamboo_plan_key"
          repo_name:
            title: Repository Name
            type: string
            description: Enter a name for your Repository
            default: "repo_name"
          bamboo_specs_build_user_admin:
            title: Admin for build project created in bamboo
            type: string
            description: Admin User ID for the Build Plan(Ex. d123456/h123456 ID)
            default: "d123456"
          bamboo_specs_build_user_nonadmin:
            title: Non Admin for build project created in bamboo
            type: string
            description: Non Admin User ID for the Build Plan(Ex. d123456/h123456 ID)
            default: "d123456"
          bamboo_specs_deployment_user1:
            title: Build plan deployment User 1
            type: string
            description: User1 ID for Deployment Plan(Ex. d123456/h123456 ID)
            default: "d123456"
          bamboo_specs_deployment_user2:
            title: Build plan deployment User 2
            type: string
            description: User2 ID for Deployment Plan(Ex. d123456/h123456 ID) 
            default: "d123456"   
      
      sonar: 
        title: SonarQube Properties
        type: object
        properties: 
          create_sonar_file:
            title: Create SonarQube File
            type: boolean
            description: Please select if you want to create sonar-project.properties or not?
            enum:
              - True
              - False
            default: True
          sonar_login:
            title: Login Token for SonarQube67
            type: string
            description: Enter Login Token for Your SonarQube67 Account
            default: "sonar_login_token"
          sonar_project_component_key:
            title: Component key of your SonarQube67 Project
            type: string
            description: Enter the Unique SonarQube67 Component Key of your Project
            default: "sonar_project_component_key"
          
      jetpack: 
        title: Jetpack Properties
        type: object
        properties:
            create_jetpack_file:
              title: Create Jetpack File
              type: boolean
              description: Please select if you want to create jetpack.yaml or not? 
              enum:
                - True
                - False
              default: True
            sonarQubeScan:
              title: Sonar Qube Scan
              type: boolean
              description: Do you want to enable Sonar Qube Scan(Choose True is yes and False if No)
              enum:
                - True
                - False
              default: True
            serviceAccess:
              title: Service Access 
              type: string
              description: Enter Service Access Permissions
              enum:
                - Public/Internet
                - Private/EDN
              default: Private/EDN
            businessUnit: 
              title: Business Unit
              type: string
              description: Enter Business Unit
              enum: 
                - Belong
                - Consumer and Small Business (C&SB)
                - Corporate Affairs 
                - Credit Management
                - Chief Risk Office Privacy (CRO)
                - Finance & Strategy (F&S) 
                - Global Contact Centres  
                - Global Enterprise Services 
                - Health', 'Human Resources 
                - Media & Marketing
                - Products (includes NBN)
                - Telstra Country Wide (TCW)
                - Telstra Digital
                - Telstra International
                - Telstra Operations
                - Telstra Wholesale
                - Technology Innovation & Strategy (TI&S)
              default: Consumer and Small Business (C&SB)
            businessCritical: 
              title: Business Critical Input
              type: boolean
              description: Choose Business Critical Settings
              enum:
                - True
                - False
              default: True
            businessRisk: 
              title: Business Risk Input
              type: string
              description: Choose Business Risk Specification
              enum:
                - Extreme
                - Severe
                - Major
                - Moderate
                - Minor
              default: Major
            informationClassification:
              title: Information Classification Input
              type: string
              description: Choose Information Classification Specification
              enum:
                - Restricted 
                - Confidential
                - Internal
                - Unrestricted
              default: Restricted
            targetPlatform: 
              title: Target Platform Input
              type: string
              description: Choose Target Platform
              enum: 
                - PCF
                - AMP Rancher
                - AMP Naked
                - Other
              default: AMP Naked
            teamGroupEmail:
              title: Team Group Email
              type: string
              description: Enter Team Group Email
              default: Stockholm@team.telstra.com
            teamLeadEmail:
              title: Team Lead Email
              type: string
              description: Enter Team Lead Email
              default: sharad.pattanshetti@team.telstra.com
            telstraType:
              title: Telstra type
              type: string
              description: Enter Telstra type
              enum:
                - Wholesale
                - Retail
                - Both
              default: Both

