apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: nodejs-microservice-template
  title:  Nodejs Microservice Template
  description: Create a nodejs microservice starter code using this template
   || Express Js  || Docker || Git Hooks  
   || Jest for Unit Test || ESLint || Sonar Qube Config || JetPack Config 
  tags:
    - experimental
    - nodejs
    - microservice
spec:
  owner: Stockholm@team.telstra.com
  templater: cookiecutter
  type: service
  path: "."
  schema:
    required:
      - component_id
      - description

    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component 

      description:
        title: Description
        type: string
        description: Description of the component
        default: NodeJS template for lambda deployment
          
      organization:
        title: Organization Details
        type: object
        properties:
          
          business_unit:
            title: Business Unit
            type: string
            oneOf:
              - const: cnsb
                title: Consumer and Small Business
              - const: te
                title: Telstra Enterprise
              - const: nit
                title: Network and IT
              - const: pt
                title: Products and Technology
              - const: gbs
                title: Global Business Services
              - const: infraco
                title: Telstra InfraCo
              - const: sf
                title: Strategy and Finance
            description: Business Unit

          domain:
            title: Domain
            type: string
            oneOf:
              - const: p2o
                title: Prospect to Order
              - const: o2a
                title: Order to Activate
              - const: u2c
                title: Usage to Cash
              - const: services
                title: Services
              - const: r2r
                title: Request to Resolve
            description: Business Domain groups a collection of systems that shares same terminology, domain-model, business-purpose, etc

        required:
        - business_unit
        - domain


      bamboo:
        title: Bamboo Specs
        type: object
        properties:

          project_key:
            title: Bamboo Project Key 
            type: string
            description: Bamboo project key (try use your existing project e.g. STOC)

          bamboo_plan_key:
            title: Bamboo Build Plan Key
            type: string
            description: Bamboo build plan key (e.g. MYSERVICEV2)

        required:
        - project_key
        - bamboo_plan_key
