apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: nodejs-lambda-template
  title: Create a nodejs lambda function using this template
  description: Create a nodejs hello world lambda function
  tags:
    - experimental
    - nodejs
spec:
  owner: Stockholm@team.telstra.com
  templater: cookiecutter
  type: service
  path: "."
  schema:
    required:
      - project_name
      - description
    properties:
      general:
        title: Project Setup
        type: object
        properties:
          project_name:
            title: Project Directory Name
            type: string
            description: Name of your project directory
            default: nodejs-lambda

          description:
            title: Description
            type: string
            description: Description of the component
            default: NodeJS template for lambda deployment

          repo_name:
            title: Repository Name
            type: string
            description: Enter a name for your Repository
            default: repo_name
          
          domain:
            title: Domain
            type: string
            oneOf:
              - const: p2o
                title: Prospect to Order
              - const: o2a
                title: Order to Activate
              - const: u2c
                title: Usage to Cash
              - const: services
                title: Services
              - const: r2r
                title: Request to Resolve
            description: Business Domain groups a collection of systems that shares same terminology, domain-model, business-purpose, etc
        required:
        - project_name
        - description
        - repo_name
        - domain
      
      organization:
        title: Organization Details
        type: object
        properties:
          business_unit:
            title: Business Unit
            type: string
            oneOf:
              - const: cnsb
                title: Consumer and Small Business
              - const: te
                title: Telstra Enterprise
              - const: nit
                title: Network and IT
              - const: pt
                title: Products and Technology
              - const: gbs
                title: Global Business Services
              - const: infraco
                title: Telstra InfraCo
              - const: sf
                title: Strategy and Finance
            description: Business Unit
        
          team_name:
            title: Team Name
            type: string
            description: Enter Your Team Name
            default: Stockholm
            
        required:
        - business_unit
        - team_name

      lambda:
        title: Lambda Function Inputs
        type: object
        properties:
          lambda_function_name:
            title: Function Name
            type: string
            description: Enter a Name for your Lambda Function
            default: lambda1
          
          runtime:
            title: Runtime
            type: string
            description: Choose runtime for your lambda function 
            enum:
              - nodejs12
              - nodejs10
            default: nodejs12      
        required:
        - lambda_function_name
        - runtime


      sonar: 
        title: SonarQube Properties
        type: object
        properties: 
          sonar_project_component_key:
            title: Component key of your SonarQube67 Project
            type: string
            description: Enter the Unique SonarQube67 Component Key of your Project
            default: "sonar_project_component_key"
        required:
        - sonar_project_component_key
        
      bamboo:
        title: Bamboo Specs
        type: object
        properties:
          project_key:
            title: Bamboo Project Key 
            type: string
            description: Bamboo project key (try use your existing project e.g. STOC)
            default: STOC
          bamboo_plan_key:
            title: Bamboo Build Plan Key
            type: string
            description: Bamboo build plan key (e.g. MYSERVICEV2)
            default: "bamboo_plan_key"
        required:
        - project_key
        - bamboo_plan_key
