apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.project_name}}
  description: {{cookiecutter.description}}
  annotations: 
    github.com/project-slug: {{cookiecutter.storePath}}
spec:
  type: service
  lifecycle: experimental
  owner: {{cookiecutter.owner}}
