Resources:
  Lambda1Role:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /
      PermissionsBoundary: 'arn:aws:iam::aws:policy/PowerUserAccess' 
      RoleName: ${self:provider.stackName}-lambda1
      AssumeRolePolicyDocument:
        Statement:
          Action:
            - 'sts:AssumeRole'
          Effect: Allow
          Principal:
            AWS: !Ref 'AWS::AccountId'
            Service:
              - lambda.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
